### ISSUE TITLE
Variant search- "need more than 0 values to unpack" issue

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1036]
https://seqr.broadinstitute.org/variant_search/results/cab7798da4b986fa7d802fa141abadee?page=1&sort=in_omim
<img width="1279" alt="Screen Shot 2019-09-26 at 7 47 54 AM" src="https://user-images.githubusercontent.com/37872186/65686270-f9c57f00-e031-11e9-9538-56c9e9b7f6ea.png">

Most dominant searches fail with the error- need more than 0 values to unpack. This error is seen across multiple projects.

A recessive search here is only returning homozygous variants- https://seqr.broadinstitute.org/variant_search/results/d4b279b3c1b9ca99c6c85a9e20af1388?page=1&sort=in_omim

**Comment by hanars** [comment]
@englandeleina reported a related case in https://github.com/macarthur-lab/seqr-private/issues/674

**Comment by hanars** [comment]
This is fixed now. It was an issue for any searches where there were no matching variants. Regarding the recessive search with only homozygous varaints, thats because there are no compound het matches: https://seqr.broadinstitute.org/variant_search/results/80efb05ced11da608c2d05fd55639ad2?page=1&sort=in_omim

If you think there should be compound het matches, thats a separate issue and you should file a new bug for it
