### ISSUE TITLE
Gene name and info missing on saved variant

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1108]
Walsh collaborators are finding saved tags with missing gene name, HGVS c., HGVS p., etc. They've seen this several times across their cohort. Example here is in Sun1.

https://seqr.broadinstitute.org/project/R0455_cmg_walsh_exomes_lispac/saved_variants/family/F026289_pac3000/Send%20for%20Sanger%20validation

<img width="1311" alt="Screen Shot 2019-12-09 at 3 56 32 PM" src="https://user-images.githubusercontent.com/44381119/70472213-bf01ad80-1a9c-11ea-86e3-6cf5874055a3.png">

**Comment by hanars** [comment]
@mike-w-wilson it looks like this is a pipeline issue, I'm seeing that variant in the index with annotated transcripts. Any ideas?

**Comment by hanars** [comment]
@mike-w-wilson any update?

**Comment by mike-w-wilson** [comment]
@stephditroia , do you have other examples of this to help us zero in on the issue?

**Comment by mike-w-wilson** [comment]
@stephditroia  @hanars  I found what was causing this. VEP annotates this variant with the consequence term "upstream_gene_variant". We omit this along with "downstream_gene_variant" consequences when we sort the transcript consequences in order to get the most severe consequence displayed. There are no other consequence terms at this site so the returned array is empty. That array is used to pull the gene symbol as we want the gene with the most severe consequence for the gene symbol. I am not sure why we omit these consequence terms though. 
https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/2a126032740075a03fbe9dc3acfb713292d543ee/hail_scripts/v02/utils/computed_fields/vep.py#L52

**Comment by hanars** [comment]
We omit them because they are really noisy and usually meaningless, and cause gene searches to return all sorts of junk. The decision to filter these consequences was made after a bunch of conversations with Daniel

**Comment by hanars** [comment]
Also, if you look at a note on the variant from the time it was tagged "This is an intronic variant in 1 transcript and an upstream UTR variant in all others . It's in a small region of conservation however." This leads me to think that when this was re-called (possibly when it was lifted to hg38) it was not called in that one transcript anymore (or the transcript disappeared entirely)

**Comment by hanars** [comment]
Closing this out as there does not appear to be anything left to do about this
