### ISSUE TITLE
HGMD update

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#1141]
Our HGMD access might go away  (or already be gone) so you might want to get an updated download if you can still access.

**Comment by bw2** [comment]
previously @sambaxter downloaded the updates through her account.

**Comment by sambaxter** [comment]
BCH/BioGrids email me a link whenever the lastest file version has been released on dropbox.  I haven't received an update since around this time last year and there isn't a repository I can search. All the links are folder specific (the last one was 2018.4). We can either request access again (https://biogrids.org/hgmd/register), if we think we've lost it, or I can reach out and see when/if the next version is being released.

**Comment by hanars** [comment]
That seems like a really old file, can we get a newer one?

**Comment by hanars** [comment]
@sambaxter any idea if we can get an updated file?

**Comment by hanars** [comment]
The latest HGMD download is now available. @mike-w-wilson can you update the reference matrix table?

**Comment by mike-w-wilson** [comment]
This is now complete. https://github.com/macarthur-lab/All-The-Envs/pull/36 and will update on the next loading.
