### ISSUE TITLE
Replace/Upgrade to Phenotips

### ISSUE THREAD

**Issue by hanars** [macarthur-lab/seqr#1162]
AnVIL req: Soft Dev Lifecycle: EOL services/dependencies

Task: Phenotips is outdated. Analysis is needed upfront to determine the best course of action 1) upgrade phenotips or 2) identify and develop the functionality provided by the service ourselves. This tasks presumes to cover completion of both the analysis and resolution activities.

Project Priority: high

Type: Tech
Task Size: large
Assignee(s): HS
Assignee Priority: 3

**Comment by hanars** [comment]
Discovery Items:
- What fields have ever been populated
- For ethnicity, do we have cases where it differs from imputed

Implementation notes:
- Will use Mondo for disorders field instead of OMIM
- info -> browse related terms UI for HPO term selection really helpful, and probably want something similar for Mondo
- show more granular HPO term details (can have nested terms for severity etc)

**Comment by hanars** [comment]
Keys to keep: 
- allergies
- apgar
- date_of_birth
- date_of_death
- disorders*
- ethnicity*
  - Broken down maternal/ paternal which we can't impute for proband only. Also we show it, also its been requested for bulk upload
- family_history
- features*
- genes*
- global_age_of_onset*
- global_mode_of_inheritance*
- life_status
- meta
- nonstandard_features
- notes
- prenatal_perinatal_history
- prenatal_perinatal_phenotype
- rejectedGenes*
- solved
- specificity

Keys to drop:
- contact
- date
- external_id
- id
- last_modification_date
- last_modified_by
- links
- reporter
- report_id
- clinicalStatus*
- sex*

**Comment by hanars** [comment]
### Patient Information
- date_of_birth
  - 3590 patients across 60 projects. projects with > 100:
    - CMG_Gleeson_Exomes: 955
    - CMG_Hildebrandt_Exomes: 476
    - Rare Genomes Project_Genomes: 182
    - CMG_Manton_Exomes : 167
    - CMG_Beggs_Exomes: 109
- date_of_death
  - 153 patients across 19 projects. projects with >= 10:
    - CMG_Scott_Exomes_Retrospective: 50
    - CMG_Scott_Exomes: 29
    -  CMG_Manton_Exomes: 18
    - CMG_Beggs_Exomes: 11
    - CMG_Wilkins-Haug_Exomes: 10
- life_status
  - either alive or deceased, set to deceased if date of death set or date of death unknown checked
  - An additional 28 deceased individuals with no specified date across 13 projects. Projects with >= 3:
    - CMG_Hildebrandt_Exomes_External_Shirlee1: 8
    - CMG_Manton_Exomes: 4
    - CMG_Gleeson_Exomes: 3
- notes.indication_for_referral
  - 1764 patients across 69 projects. projects with > 50:
    - CMG_Hildebrandt_Exomes: 428
    - CMG_Manton_Exomes: 187
    - CMG_Beggs_Exomes: 88
    - INMR neuromuscular disease exomes: 56
    - CMG_Hildebrandt_Exomes_External_Shirlee1: 53

### Family history
- notes.family_history (List health conditions found in family)
- family_history
  - consanguinity, miscarriages, affectedRelatives

### Prenatal/ perinatal history
- prenatal_perinatal_history
  - multipleGestation, gestation, assistedReproduction_fertilityMeds, assistedReproduction_iui,  ivf,  icsi, assistedReproduction_surrogacy, assistedReproduction_donoregg, assistedReproduction_donorsperm, maternal_age, paternal_age
- apgar
- prenatal_perinatal_history.obstetric-history

### Clinical symptoms / physical findings
- nonstandard_features

### Diagnosis
- notes.diagnosis_notes

**Comment by sambaxter** [comment]
Sam's opinion on what to keep
**Patient Information**
date_of_birth - yes
date_of_death - yes
life_status - yes (I would prefer this to be background logic that is calculated based on birth/death rather than being a manual field) - either alive or deceased, set to deceased if date of death set or date of death unknown checked

notes.indication_for_referral - need to have some sort of notes field regrading phenotype and disease. 

**Family history**
Family history - yes

family_history.miscarriages - we wouldn't expect most of our affecteds to have yes, we would expect it to be primarily the unaffected mothers.  This is a very common genetic counseling question, we can put this up to the analysts and RGP staff to decide if they use this.  There is an HPO term for this (https://mseqdr.org/hpo_browser.php?200067;)

family_history.affectedRelatives - I am leaning towards yes and have it default to yes if there is more than two affecteds entered into seqr

**Prenatal/ perinatal history**
prenatal_perinatal_history.multipleGestation - no

prenatal_perinatal_history.gestation  - no 

prenatal_perinatal_history: assistedReproduction fields - yes (RGP uses this)
Includes assistedReproduction_fertilityMeds, assistedReproduction_iui, ivf, icsi, assistedReproduction_surrogacy, assistedReproduction_donoregg, assistedReproduction_donorsperm

prenatal_perinatal_history.maternal_age - no, check with analysts

prenatal_perinatal_history.paternal_age - no, check with analysts

apgar - no

prenatal_perinatal_history.obstetric-history- no

**Clinical symptoms / physical findings**
nonstandard_features - yes

**Diagnosis**
notes.diagnosis_notes - wrap up to other notes field

**Comment by hanars** [comment]
All phenotips data was moved directly to model fields in seqr (https://github.com/macarthur-lab/seqr/pull/1260/files), all connections to the phenotips server were removed in favor of those fields (https://github.com/macarthur-lab/seqr/pull/1284/files), all deployment code for phenotips was removed (https://github.com/macarthur-lab/seqr/pull/1315/files), and on 6/5/202 the running phenotips pod was deleted and the database was dropped
