### ISSUE TITLE
Unable to unselect a gene

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1216]
**Describe the bug**
Unable to unselect a gene

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F024438_rgp_587/matchmaker_exchange

**Scope of the bug**
So far, only this case

**Screenshots**
![Screen Shot 2020-03-12 at 8 12 20 AM](https://user-images.githubusercontent.com/37872186/76520557-7c53c680-6439-11ea-8d0a-3f07a63dfc6c.png)

**Comment by hanars** [comment]
So this is a bug with how the checkbox is displayed, but in the background it is correctly unselecting it, so if you click the row and it is no longer dark grey but still is checked it is actually unselected. To test this I removed GPX2 successfully from this submission (so if you didn't want to do that you should probably go back and fix it). Keeping this issue open since this clearly needs to be fixed, but at least in the meantime there is a workaround

**Comment by hanars** [comment]
fixed
