### ISSUE TITLE
400 error

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1455]
400 error when searching for variants in the Thaker cohort.  

It seems to be affecting many families. 

Example 1: https://seqr.broadinstitute.org/variant_search/results/252f6d253af72d60d5e5b338e4868973?page=1&sort=xpos
<img width="1175" alt="Screen Shot 2020-09-22 at 11 30 35 AM" src="https://user-images.githubusercontent.com/37872186/93903736-0f15cd80-fcc7-11ea-8887-bdd448dc7e1a.png">
<img width="1175" alt="Screen Shot 2020-09-22 at 11 30 35 AM" src="https://user-images.githubusercontent.com/37872186/93903919-3cfb1200-fcc7-11ea-8c83-007f195d7732.png">

Additonally, a project wide search is also resulting in a 400 error- https://seqr.broadinstitute.org/variant_search/results/f20f8e5d883eb59b30b4a091a88f1e6b?page=1&sort=xpos

<img width="1177" alt="Screen Shot 2020-09-22 at 11 32 08 AM" src="https://user-images.githubusercontent.com/37872186/93903950-46847a00-fcc7-11ea-8f47-7befdf46f942.png">

Pls excuse my formatting, I don't see the usual prompts. I tried to include all relevant information.

**Comment by hanars** [comment]
There appears to be an issue where some families in this project had data loaded previously but no longer have data loaded. The family in the first search is one such family, if you look at the page you will now see that all the dots next to the individuals are grey instead of green. This is an issue for the PM/ data loading teams.

The second search is now working

**Comment by lynnpais** [comment]
Thanks for looking into it. Did you notify the PM team or shall I?

**Comment by hanars** [comment]
I have not let them know, I don't like being involved in sample issues
