### ISSUE TITLE
don't show genes with "upstream/downstream gene" functional annotations

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/seqr#408]
(unless they're explicitly selected in the functional annotation filter)

**Comment by hanars** [comment]
We should also address https://github.com/macarthur-lab/seqr/issues/229

**Comment by hanars** [comment]
Should also address https://github.com/macarthur-lab/seqr/issues/356

**Comment by hanars** [comment]
Now we only show the gene associated with the "worst" transcript which fixes this issue. Leaving https://github.com/macarthur-lab/seqr/issues/229 open because we may want to revisit this in the future, and particularly with regards to searches where the variant is now matching on criteria that is not being shown by default (i.e. matching a gene or consequence that are not the "worst" and therefore are not shown )

**Comment by hanars** [comment]
We decided to go back to showing all genes,  so this is still an issue. We should remove these transcripts in the pipeline

**Comment by hanars** [comment]
This is fixed by https://github.com/macarthur-lab/hail-elasticsearch-pipelines/pull/87 so all future data loading will not have upstream/downstream annotations
