### ISSUE TITLE
Variant bar in 2 rows

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#512]
This is just a suggestion. Given the variant bar is so dominated by review/exclude tags, I wonder if we could have these in a separate row from all the other tags: 

![image](https://user-images.githubusercontent.com/10407888/43485599-a38230aa-94df-11e8-9323-378b4c2d91fb.png)

Like this: 
![image](https://user-images.githubusercontent.com/10407888/43485678-e0e2cc3e-94df-11e8-9280-b77004900c0b.png)

**Comment by hanars** [comment]
So based on a suggestion from @alovgren I just added an update so it hides the excluded tags from the bar when the "hide excluded" checkbox is toggled. I don't think we would actually want to create a similar "hide review" option for the page, because a lot of the time people leave the review tag on a variant that has had other tags added to it. But maybe we could add a "hide review only" option that would hide all variants whose only tag is "review" and would hide the review section from the bar? Or we could add a toggle next to the bar that just hides review from the bar. Or we could get rid of the update that hides excluded from the bar and do what you suggest here and have 2 bars. Thoughts?

**Comment by hanars** [comment]
re: seeing  (Tier 1 + Tier 2 + known) how does that differ from applying the "CMG Discovery Tags" filter?

**Comment by anneodonnell** [comment]
If that's a planned feature, it's probably a redundant suggestion. I guess one minor thing is it would be nice to see CMG discovery tags with or without known gene tags also

**Comment by hanars** [comment]
That already exists, at the top of the page there is a dropdown where it says "Showing X of Y  "category/tag" variants" and you can select "CMG Discovery Tags"

**Comment by anneodonnell** [comment]
Oh nice - I didn’t realize that was already a feature. We should make sure the other analysts know but yes, that addresses my request. Hide review only would also still be helpful.

**Comment by hanars** [comment]
The "hide review only"filter has been added
