### ISSUE TITLE
Change call set filtering default for small callsets

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#591]
If the callset if very small, the default 1% AF does cause problems - if your call set if 1 trio, then AN = 6 so AC = 1 is 16%. 

Is there some way to disable callset filtering for callsets below a certain size? I'd probably want to disable it for callsets AN 400 (as a homozygous variant in a trio in a callset this size would be AC = 4 at a minimum and 1% AF). You could disable by removing/hiding or setting to 100%. 

Another option would be to put a warning label by call set filtering for small callsets. 

This came up because Miriam has a single trio in seqr (not sure why it wasn't called with the rest of the CMG data) but Sek paid for the sequencing because it doesn't qualify for data sharing - and she wasn't finding any variants at all in her searches because the default was set to 1% AF.

**Comment by bw2** [comment]
As a temporary fix, what do you think about changing the default to 1 instead of 0.01 for all projects?

**Comment by anneodonnell** [comment]
That would mean for 95+% of analysis, we'd have to manually change it. I'd rather it be set for the majority of cases rather than the minority, personally.


On Sep 27, 2018, at 2:15 PM, bw2 <notifications@github.com<mailto:notifications@github.com>> wrote:


As a temporary fix, what do you think about changing the default to 1 instead of 0.01 for all projects?

-

**Comment by bw2** [comment]
This is going to come up with local installs also, but it's non-trivial to get the AN right now so can leave it to @hanars and use "number of individuals > 200" as a proxy for now.

**Comment by hanars** [comment]
@anneodonnell do you think this is still an issue in new search? Should we add some sort of default search for small callsets?

**Comment by anneodonnell** [comment]
I think if a callset has <100 people (AN = 200), we'd want to default the callset filter to 100% (1.0). For anything bigger, I say we just leave it as standard. I'm not sure how hard something like that would be to implement though - it will only affect the smaller stand alone projects so it's not top priority but it would be nice if we could do this.

**Comment by hanars** [comment]
Sorry, I should clarify what I meant: there are the 3 built-in saved searches that you and Alysia worked out that everyone in seqr has access to. I was asking if you think having a couple additional ones with an even higher threshold for the "this callset" filter is a good idea. That way people analyzing a smaller callset could choose those out of the box. As an alternative, they could edit that filter and save their own search, which might make more sense since this effects so few projects.

There is really no concept of "defaults" in search anymore- when you get to the search page nothing is pre-selected. There are only saved searches, and the options for those are a built-in that everyone gets, or individuals saving their own. Therefore, I'm not entirely sure what to do with this ticket

**Comment by hanars** [comment]
@anneodonnell any thoughts? Is this ticket moot at this point? Or do you think I should add a default search that has more relaxed "this callset" filters?

**Comment by anneodonnell** [comment]
I think it's mostly moot at this point given it starts at 1 and is set reasonably in the default searches. If someone tries to use a default search on a small project, they will still run into problems. We could have searches for small callsets but I don't really want to clutter up the searches so I don't feel strongly about including that.

**Comment by hanars** [comment]
Okay sounds good, I'll close this out
