### ISSUE TITLE
Request to change default view for saved variants

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#604]
Hello,

The analysts would like to have the default view for saved variants changed to those marked with a Review, Analyst high priority and/or Discovery tag only. It is currently set to all saved (includes those with just a note and no tag). 
<img width="1309" alt="screen shot 2018-10-11 at 11 17 40 am" src="https://user-images.githubusercontent.com/37872186/46814852-9c182400-cd47-11e8-92f7-b09c5f94b7d4.png">

**Comment by hanars** [comment]
When you say you want to update "the default view", can you explain what you mean or how you are getting to that page? Do you mean what shown up when you click "View all" on the project page?

**Comment by hanars** [comment]
Hi @lynnpais can you follow up with more details for this issue?

**Comment by hanars** [comment]
Hi Lynn, again, it is not clear to me what you mean by "default", as whether or not to show notes is not something that gets turned on or off. This is the "all saved" page, which shows all variants that have been saved. If I made this change then how would you ever view variants that have notes and no tags?

 If you are trying to view tagged variants, you can do this by viewing the variants with a specific tag or with a given category (for example, all the variants with a discovery tag).  Can you elaborate on the use case for viewing all variants that have any sort of tag that is being complicated by the presence of variants with notes? 

My recommendation would be that if there are variants that you do not want to see that you add the excluded tag to them, and then use the "hide excluded" option so they do not show up, rather than not showing any tags with notes

**Comment by hanars** [comment]
Closing this do to lack of actionability
