### ISSUE TITLE
Show reads

### ISSUE THREAD

**Issue by kounap** [macarthur-lab/seqr#652]
I cannot see reads in Estonian Seqr cohort. All three windows are opening (patient and parents), but they are empty. Actually I had same problem often at home, but I thought that this is caused that we looked it far away. We just solved in this way that Sander looked candidate directly from bam files.
This is a problem in CMG_Estonia_WGS as the whole cohort. I clicked many cases through the whole project and could not possible to any reads. However, I did not look all cases.
Ellie wrote about 104 in last week in the same issue.
Due to that I looked other projects too. I cannot open anymore Estonian external exomes and CMG_Estonia_WES reads anymore too. It worked in previous weeks with external exomes when we did reanalysis of new cases. It worked before in previous weeks. 
I closed program, opened, refreshed, tried to change web program, but it is not working,

**Comment by hanars** [comment]
Thanks for letting me know. Because Ellie already made a ticket (which you can see here https://github.com/macarthur-lab/seqr/issues/645) I am going to close this one so I can keep track of progress on this issue in one place. I have updated that ticket to include the additional information you provided here
