### ISSUE TITLE
Variant search not working for samples moved between families

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#678]
A couple of samples in the Pierce cohort were moved between families (such as PIE_OGI709_001414_1 from OGI709 to OGI1213 and PIE_OGI269_000576_1 into OGI841) using the new family renaming feature. A collaborator followed up trying to analyze the newly corrected family and found that variant searches aren't working. It looks like the moved samples are showing up as no call and are messing up family-wide searches for anything dependent on their genotype.

The VCF for these samples seems to be fine and Mike has been able to successfully run relatedness checks since the move.

I've heard Eleina has also had issues on this with Myoseq samples, and those may be the ones that Ben moved over the summer. I'll follow up once I can confirm this with her and Jaime.

Thanks!

**Comment by hanars** [comment]
Hi Katie, can you please provide a complete list of the families experiencing this problem

**Comment by hanars** [comment]
@mike-w-wilson this is an issue with the way the elasticsearch index got split. Seqr requires all individuals in a family to be in the same index, but the existing sample in that family is in r0284_pierce_retinal_degenerat__wes__grch37__variants__20180924_2 and the new sample that got moved is in r0284_pierce_retinal_degenerat__wes__grch37__variants__20180924_1. Unfortunately, I think the only way to fix this is to reload the data

Going forward this should not be an issue, because all data loaded using the new --use-child-docs-for-genotypes schema gets loaded into a single index

**Comment by hanars** [comment]
(Also Katie I don't need the full list of families, they will all have the same issue)

**Comment by mike-w-wilson** [comment]
@katie-larkin This project has been reloaded and search now returns calls for all samples.
