### ISSUE TITLE
Manton external collaborator search issue

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#824]
Casie just wrote me this email about CMG_Manton_Exomes:

"We are having a seqr and I’m not sure who to contact about it. I have Shira’s permissions set to manager for Manton CMG, which is the same as me, but when she goes to do a variant search it is say access denied…"

**Comment by hanars** [comment]
Hi Katie, 

Can you please get me some additional information:
- The email address(s) of the person/people who cannot access projects
- Which projects they expect to access
- What happens when they go to the project page
- "when she goes to do a variant search " - is this a specific family? for all families? Ideally, a screenshot of the error they are seeing would be helpful

**Comment by katie-larkin** [comment]
The issue is with Shira Shira.Rockowitz@childrens.harvard.edu. 

Here's a screenshot I have already. I'll update with the answers to your questions when I get them. 

My guess looking at the url is that they're not accessing the right seqr project. I gave the a link to the family page of MAN_0009 in CMG_Manton_Exomes and asked them to try that.
![image001](https://user-images.githubusercontent.com/43212980/56614415-fa6f6a80-65e6-11e9-9128-9391b2866a00.png)

**Comment by katie-larkin** [comment]
The link to CMG_Manton_Exomes loads properly. Shira was using https://seqr.broadinstitute.org/project/manton_orphan-diseases_cmg-samples_exomes_v1/family/MAN_0009/mendelian-variant-search, which gives her the permission denied error, but works for me and says it is from CMG_Manton_Exomes

**Comment by hanars** [comment]
Okay this should be resolved
