### ISSUE TITLE
Variant search for RGP_441 not working

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#828]
401 appears at the bottom of the page when trying to run a typical search- https://seqr.broadinstitute.org/variant_search/results/189607ca759458b9f3ec59aeb8a49616?page=1&sort=xpos
![Screen Shot 2019-04-24 at 4 12 57 PM](https://user-images.githubusercontent.com/37872186/56690604-db86dc00-66ab-11e9-85b8-ad7220f764d8.png)

**Comment by hanars** [comment]
So that link is (somehow) to a search where you just search for recessive variants with no other filters applied, which is causing huge timeouts/ issues. I don't really know how that happened, but heres a link to the search I think you were trying to run (it returned no results): https://seqr.broadinstitute.org/variant_search/results/f7383a93ecc38990222109c9b57e1766?page=1&sort=xpos
 Heres a link to that same search but where I only consider one of the individuals affected, which does return results:
https://seqr.broadinstitute.org/variant_search/results/cd82df71cc6ffd4f01f50e17c4ede2c4?page=1&sort=xpos

I still don't understand how that link was so far off from the search you thought you did but I'm going to mark this issue as closed
