### ISSUE TITLE
504 error engle wgs 900

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#832]
https://seqr.broadinstitute.org/variant_search/results/7f4188ed5069ce968b4f62f60c5f98aa?page=1&sort=cadd

Standard AR search across engle 900 cohort, search space limited to just a handful of genes. getting 504. Thanks!

**Comment by hanars** [comment]
Unfortunately, compound het searches do not scale very well, which is why that search is timing out. If you change it to homozygous recessive it works fine (https://seqr.broadinstitute.org/variant_search/results/fdbeef62b66ad8a114ca18f7b4851a66?page=1&sort=cadd ). 

Also,  the ab and gq filters sometimes really slow down search, especially for compound hets. If you remove those, the search completes (https://seqr.broadinstitute.org/variant_search/results/a64f3e314f38c89ac9dd20552641514c?page=1&sort=xpos)
