### ISSUE TITLE
Frameshift variant filtered out incorrectly

### ISSUE THREAD

**Issue by gvannoy** [macarthur-lab/seqr#877]
In RGP_256 an initial search with parameters: [Inheritance - Recessive, Location - DEGS1, Call Quality - GQ: 20, AB: 25]  yields 16 variants: 12 intronic, 3 3prime UTR, and 1 frameshift
(search link: https://seqr.broadinstitute.org/variant_search/results/8cfd5bc58a0d726d4e423d414cd2f521?page=1&sort=pathogenicity)

A second search with the same parameters as above PLUS [Annotations: Frameshift] yields 0 variants. 
(search link: https://seqr.broadinstitute.org/variant_search/results/8ef2ac697460ccf471457910c905bc5f?page=1&sort=pathogenicity)

**Comment by hanars** [comment]
This is because in that first search the variant was returned as part of a compound het. When you apply the frameshift filter, it only looks for compound hets in variants with the filtered consequences, and since there is only one hit with that consequence that no longer counts as a compound het and so nothing is returned.
