### ISSUE TITLE
504 error for special searches

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#910]
https://seqr.broadinstitute.org/variant_search/results/6ce472f687e7af8f8fe17b413eecc0b7?page=1&sort=xpos
<img width="1224" alt="Screen Shot 2019-06-18 at 11 04 10 AM" src="https://user-images.githubusercontent.com/37872186/59695815-d9776000-91b8-11e9-9489-831622233aa6.png">

I know we briefly talked about this with Eleina, but I thought I'd send you another example. Here, I am unable to analyze the sibs independently.

**Comment by hanars** [comment]
So the issue is we do not have sequencing data for WAL_MC41900_MC41901_D1. So when you set the other 2 to unknown, you've created a family with no affected individuals and it tries to return a ton of variants and crashes. If you analyze the other 2 affected children independently, search works fine:
https://seqr.broadinstitute.org/variant_search/results/4de068e675663f79162be23b41ca5ab5?page=1&sort=xpos
https://seqr.broadinstitute.org/variant_search/results/8e1b7eac0b88c3bed7537a4c0853cecc?page=1&sort=xpos
