### ISSUE TITLE
Gene Search 504

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#976]
Hi Hana,

I am not sure why my gene searches end up in 504s, while yours go through. Here's one more example-https://seqr.broadinstitute.org/variant_search/results/bd8e5e6eb45e0a2901b8954430ab1549

Can we set up some time today to trouble shoot? I'm available most of the day. 

Thank you!

Lynn

**Comment by hanars** [comment]
Hi Lynn, 

Sometimes gene searches go through for me and not you because sometimes they timeout the first time you try but succeed the second time. In general, it might be best to wait 5-10 minutes and try a search again before submitting an issue.

In this case, that search also times out for me. For really large scopes like this ( you are looking at over 2500 families!), I highly recommend doing a search without an inheritance mode, which is a substantially faster search than a recessive search. For example, for the search you were doing as an all inheritance search completed really quickly for me and only returned 24 variants so it should be pretty quick to determine which if any have the inheritance you care about:
https://seqr.broadinstitute.org/variant_search/results/dc749fa1be8d732ba7b5cab54adaec89?page=1&sort=xpos
