### ISSUE TITLE
SRGAP2 constraint information

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#991]
SRGAP2 is both missense and LoF constrained, but there's no tag in seqr? 
![Screen Shot 2019-08-14 at 9 17 34 AM](https://user-images.githubusercontent.com/37872186/63024086-7c282400-be74-11e9-96d8-299cd528cbec.png)
![Screen Shot 2019-08-14 at 9 17 40 AM](https://user-images.githubusercontent.com/37872186/63024088-7d595100-be74-11e9-99a4-d003d00fe000.png)

https://seqr.broadinstitute.org/project/R0481_cmg_gleeson_wgs/saved_variants/family/F025895_3165

**Comment by hanars** [comment]
So there are 2 different ensembl IDs that have the name SRGAP2: 
https://seqr.broadinstitute.org/gene_info/ENSG00000266028 and https://seqr.broadinstitute.org/gene_info/ENSG00000163486

One of those is the one that is constrained in gnomad, the other is the one that your variant is actually annotated in. The ccordinates for these genes are different, and if you look your variant is not in the constrained gene. If you click on the gnomad link on your variant, it actually does not take you to the page you show here.

This is, objectively, really confusing. I am closing out this issue because there is nothing actionable I can do to help right now. However, if you and the analysis team can come up with any ways that seqr can make this more clear, please submit another issue with those ideas
